title: Hello World6
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://khoprujan.github.io/about/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: test
   url: /test

social:
   github: khoprujan
   email: khoprujan@gmail.com

google_analytics: "UA-58263416-1"
